steps:
  - name: "gcr.io/kaniko-project/executor:latest"
    args:
      - --destination=gcr.io/$PROJECT_ID/hackathon-sepro:$COMMIT_SHA
      - --context=/workspace/front-buyer/
      - --cache=true
      - --cache-ttl=263520h
    dir: "front-buyer"

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "hackathon-sepro"
      - "--image"
      - "gcr.io/$PROJECT_ID/hackathon-sepro:$COMMIT_SHA"
      - "--memory"
      - "128Mi"
      - "--allow-unauthenticated "
      - "--region"
      - "southamerica-east1"
      - "--port"
      - "80"
